### ISSUE TITLE
:width and :height are not respected on reagent rendered graphs

### ISSUE THREAD

**Issue by diegovdc** [metasoarous/oz#105]
I might be doing something wrong, but I am trying to set the width for a graph rendered by reagent and although there is an effect (the graph gets wider or higher), the precise width does not correspond to the one given. E.g. I am setting a width of `500px` and the resulting width of the canvas is `613px`.

I also tried using the `"container"` value (as specified [here](https://vega.github.io/vega-lite/docs/size.html)), because I would actually prefer very much to have a responsive visualization, but then the graph collapses (I also tried to use the value as `:container` with no luck).

This is my code: https://github.com/diegovdc/covid-spread/blob/master/src/codiv_spread/core.cljs#L71-L78

And you can see the deployment here https://quihubolecontupandemia.netlify.com/

Am I missing something?

**Comment by wongjoel** [comment]
I think the reason the canvas is bigger than the set width is due to the property `autosize` defaulting to `pad`, so it actually makes the plot bigger to render the axes and labels (I think you need to set `autosize` to `fit` to make it strictly fit within the given size.

For using the `container` value, I think (as being discussed in #74) that it collapses because the containing div doesn't have a size set.

**Comment by metasoarous** [comment]
Thanks for reporting this @diegovdc.

I think @wongjoel is correct that you just need to use the `autosize` property to get the total dimensions to match your expectations (as apposed to just the plot area itself).

As @wongjoel additionally points out, the `container` dimension settings in `vega` currently do not work, because the div we attach them to does not have style. We're tracking this in #74, and I'm hoping to address that issue soon.

For now, I'm going to close this, but please reopen if you continue to have an issue (or if we've misunderstood) once #74 is resolved.

Thanks again!
