### ISSUE TITLE
about the usage of oz

### ISSUE THREAD

**Issue by drorbemet** [metasoarous/oz#61]
Hi, first let me thank you a lot for this great project. It encouraged
me to continue to gather the pieces needed to do data-science in
clojure. 
Although my question so far has been: Is oz ment to be uses as a project
or a library?

**Comment by metasoarous** [comment]
Hi @drorbemet. Thank you so much, both for the feedback and for trying it out in the first place.

Primarily, it's designed to be used as a library.

I'm assuming that by "as a project" you mean something that you could fork/clone and work from as a template? You can certainly do that if you like, and would afford the advantage of giving you an Oz development environment set up so that you could either customize or contribute back to the project with features as they become useful to you. But to put a clear point on it, all of the advertised functionality of Oz is available through the library API, so you certainly aren't required to fork/clone to take full advantage of anything.

In the future, I may put together a project generator to help get a project set up easily.

Please let me know if I understood your question accurately, and if there's anything else I can clarify.

Thanks again!

**Comment by drorbemet** [comment]
Yes, thanks.
