### ISSUE TITLE
Running in Docker

### ISSUE THREAD

**Issue by alanmarazzi** [metasoarous/oz#70]
Hey there, I was trying to run Oz from a Docker container which is the only deploy option I have at the moment, but when I try to `start-server!` I get this error:

```java
19-06-27 09:03:29 UnknownHost INFO [oz.server:139] - Web server is running at `http://localhost:10666/`
Execution error (IOException) at java.lang.UNIXProcess/forkAndExec (UNIXProcess.java:-2).
error=2, No such file or directory
java.io.IOException: Cannot run program "xdg-open": error=2, No such file or directory
```
To reproduce the problem this is my Dockerfile:

```dockerfile
FROM clojure:openjdk-8-tools-deps

EXPOSE 10666
EXPOSE 8888

RUN echo '{:deps {nrepl/nrepl {:mvn/version "0.6.0"} cider/cider-nrepl {:mvn/version "0.21.1"} metasoarous/oz {:mvn/version "1.6.0-alpha3"}} :aliases {:nREPL {:extra-deps {nrepl/nrepl {:mvn/version "0.6.0"}}}}}' > deps.edn &&\
    echo '{:bind "0.0.0.0" :port 8888}' > .nrepl.edn &&\
    clj -Sforce < /dev/null >&0

CMD ["clj", "-R:nREPL", "-m", "nrepl.cmdline", "--middleware", "[cider.nrepl/cider-middleware]"]
```
My money is on the lack of a browser, one possible solution is to give a `:no-browser` option to `start-server!`

**Comment by alanmarazzi** [comment]
I confirm that by adding 

```dockerfile
RUN apt-get update && apt-get install -y xdg-utils --fix-missing
```
to the above Dockerfile Oz works. Of course it doesn't make much sense to install `xdg` in a container, but it is good to know that there is some kind of workaround

**Comment by stardiviner** [comment]
@alanmarazzi Will Oz provide officially Docker image?

**Comment by alanmarazzi** [comment]
@stardiviner no clues, you should ask @metasoarous

**Comment by metasoarous** [comment]
Hi folks. Thanks for raising this issue @alanmarazzi.

I now have this set up so that if the browser fails to open, it simply prints out a message asking you to open your browser to the url corresponding to the port you've used.

@stardiviner There isn't an official docker image right now, however you can take a look at https://github.com/pol-is/analysis. This is where I've been using Oz with Docker. I'd be happy for someone to put together a more stripped down Docker image, but it's kinda low priority for me right now.

Thanks again!

**Comment by stardiviner** [comment]
@metasoarous I see. Thanks for your hints. I will check it out.
